Update zh_cn.json
Aizistral-Studios/No-Chat-Reports pull request #91
Opened 2022-07-23 01:30 UTC by fire12324344

Updated Simplified Chinese translation

2022-07-23 11:46 UTC, Aizistral approved these changes

2022-07-25 06:55 UTC, Taskeren requested changes
🇺🇸 
A low quality translation.

Line 5 contains a Traditional Chinese word "服務器" which should be "服务器" instead.
Line 11 has a space at the beginning.

DO NOT USE GOOGLE TRANSLATE OR OTHER TRANSLATOR!

🇨🇳 
翻得什么玩意，能不能不要去污染别人的仓库。

2022-07-25 09:50 UTC, Aizistral commented
@Taskeren, maybe make your own pull request? I do not have the knowledge of the language to review translations, but I trust your expertise.

2022-07-27 20:07 UTC, Aizistral commented
Closed in favor of #99.

2022-07-27 20:07 UTC, closed without merging